/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quake_two_android_Quake2_QuakeRenderer */

#ifndef _Included_quake_two_android_Quake2_QuakeRenderer
#define _Included_quake_two_android_Quake2_QuakeRenderer
#ifdef __cplusplus
extern "C" {
#endif
#undef quake_two_android_Quake2_QuakeRenderer_STATE_RESET
#define quake_two_android_Quake2_QuakeRenderer_STATE_RESET 0L
#undef quake_two_android_Quake2_QuakeRenderer_STATE_SURFACE_CREATED
#define quake_two_android_Quake2_QuakeRenderer_STATE_SURFACE_CREATED 1L
#undef quake_two_android_Quake2_QuakeRenderer_STATE_RUNNING
#define quake_two_android_Quake2_QuakeRenderer_STATE_RUNNING 2L
#undef quake_two_android_Quake2_QuakeRenderer_STATE_ERROR
#define quake_two_android_Quake2_QuakeRenderer_STATE_ERROR 100L
#ifdef __cplusplus
}
#endif
#endif
