/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeus_arena_KwaakJNI */

#ifndef _Included_org_zeus_arena_KwaakJNI
#define _Included_org_zeus_arena_KwaakJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    enableAudio
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_enableAudio
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    enableBenchmark
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_enableBenchmark
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    enableLightmaps
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_enableLightmaps
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    enablePureServers
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_enablePureServers
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    enableOpenArenaProtocol
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_enableOpenArenaProtocol
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    setAudio
 * Signature: (Lorg/zeus/arena/KwaakAudio;)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_setAudio
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    showFramerate
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_showFramerate
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    initGame
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_initGame
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    setLibraryDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_setLibraryDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    drawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_drawFrame
  (JNIEnv *, jclass);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    queueKeyEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_queueKeyEvent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    queueMotionEvent
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_queueMotionEvent
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    queueTouchEvent
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_queueTouchEvent
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    queueTrackballEvent
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_queueTrackballEvent
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    requestAudioData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_requestAudioData
  (JNIEnv *, jclass);

/*
 * Class:     org_zeus_arena_KwaakJNI
 * Method:    setRenderer
 * Signature: (Lorg/zeus/arena/KwaakRenderer;)V
 */
JNIEXPORT void JNICALL Java_org_zeus_arena_KwaakJNI_setRenderer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
