/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeus_arena_Game */

#ifndef _Included_org_zeus_arena_Game
#define _Included_org_zeus_arena_Game
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeus_arena_Game
 * Method:    RegisterThis
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_zeus_arena_Game_RegisterThis
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
