/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quake_two_android_Quake2_QuakeView_QuakeButton */

#ifndef _Included_quake_two_android_Quake2_QuakeView_QuakeButton
#define _Included_quake_two_android_Quake2_QuakeView_QuakeButton
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
