/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class quake_two_android_Quake2 */

#ifndef _Included_quake_two_android_Quake2
#define _Included_quake_two_android_Quake2
#ifdef __cplusplus
extern "C" {
#endif
#undef quake_two_android_Quake2_MSG_SHOW_DIALOG
#define quake_two_android_Quake2_MSG_SHOW_DIALOG 1L
#undef quake_two_android_Quake2_DIALOG_EXIT_ID
#define quake_two_android_Quake2_DIALOG_EXIT_ID 0L
#undef quake_two_android_Quake2_DIALOG_ABOUT_ID
#define quake_two_android_Quake2_DIALOG_ABOUT_ID 1L
#undef quake_two_android_Quake2_DIALOG_PAK_NOT_FOUND
#define quake_two_android_Quake2_DIALOG_PAK_NOT_FOUND 2L
#undef quake_two_android_Quake2_DIALOG_ERROR
#define quake_two_android_Quake2_DIALOG_ERROR 3L
#undef quake_two_android_Quake2_DIALOG_LOADING
#define quake_two_android_Quake2_DIALOG_LOADING 4L
#undef quake_two_android_Quake2_DIALOG_CHECK_UPDATE
#define quake_two_android_Quake2_DIALOG_CHECK_UPDATE 5L
#undef quake_two_android_Quake2_MOVE_NOTHING
#define quake_two_android_Quake2_MOVE_NOTHING 0L
#undef quake_two_android_Quake2_MOVE_FORWARDMOVE
#define quake_two_android_Quake2_MOVE_FORWARDMOVE 1L
#undef quake_two_android_Quake2_MOVE_YAW
#define quake_two_android_Quake2_MOVE_YAW 2L
#undef quake_two_android_Quake2_MOVE_VIEW
#define quake_two_android_Quake2_MOVE_VIEW 3L
#undef quake_two_android_Quake2_PITCH_DEFAULT
#define quake_two_android_Quake2_PITCH_DEFAULT -50.0f
/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2GetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_quake_two_android_Quake2_Quake2GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2Init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2Init
  (JNIEnv *, jclass);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2Frame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2Frame
  (JNIEnv *, jclass);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2Quit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2Quit
  (JNIEnv *, jclass);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2Test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2Test
  (JNIEnv *, jclass);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2SetWidth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quake_two_android_Quake2_Quake2SetWidth
  (JNIEnv *, jclass, jint);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2SetHeight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quake_two_android_Quake2_Quake2SetHeight
  (JNIEnv *, jclass, jint);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2SetOverlay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_quake_two_android_Quake2_Quake2SetOverlay
  (JNIEnv *, jclass, jint);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2PaintAudio
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2PaintAudio
  (JNIEnv *, jclass, jobject);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2GetDisableScreen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2GetDisableScreen
  (JNIEnv *, jclass);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2GetVibration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2GetVibration
  (JNIEnv *, jclass);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2KeyEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_quake_two_android_Quake2_Quake2KeyEvent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2MoveEvent
 * Signature: (IIIIFFF)V
 */
JNIEXPORT void JNICALL Java_quake_two_android_Quake2_Quake2MoveEvent
  (JNIEnv *, jclass, jint, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     quake_two_android_Quake2
 * Method:    Quake2Paused
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_quake_two_android_Quake2_Quake2Paused
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
